global using Xunit;
global using server.Infrastructure;
global using server.Core;
global using server.Core.EF;
global using server.Core.EF.DTO;
global using server.Core.EF.RepositoryInterfaces;
global using Microsoft.Data.Sqlite;
global using Microsoft.EntityFrameworkCore;
global using Moq;
